spring.application.name=SirmaFinalExam
spring.datasource.url=jdbc:sqlserver://localhost:59161;databaseName=springUser;encrypt=false;
spring.datasource.username=springUser
spring.datasource.password=newPass123.
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true